SELECT a.ITEM_ID, a.ITEM_NAME, a.RARITY
FROM ITEM_INFO a, ITEM_TREE b
WHERE a.ITEM_ID = b.ITEM_ID AND b.ITEM_ID IN (SELECT b.ITEM_ID FROM ITEM_TREE b WHERE b.ITEM_ID NOT IN (SELECT DISTINCT(b.PARENT_ITEM_ID) FROM ITEM_TREE b WHERE PARENT_ITEM_ID IS NOT NULL))
ORDER BY ITEM_ID DESC;