SELECT A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE * (1- (P.DISCOUNT_RATE / 100)) * 30, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A 
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON A.CAR_TYPE = P.CAR_TYPE
WHERE 
    A.CAR_TYPE IN ('세단', 'SUV')
    AND P.DURATION_TYPE = '30일 이상'
    AND A.DAILY_FEE * (1 - (P.DISCOUNT_RATE / 100)) * 30 BETWEEN 500000 AND 2000000
    AND A.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE >= '2022-11-01' AND START_DATE < '2022-12-01'
)
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC