-- 코드를 입력하세요
SELECT B.USER_ID, B.NICKNAME, CONCAT(B.CITY, ' ', B.STREET_ADDRESS1,' ', STREET_ADDRESS2) '전체주소', CONCAT(LEFT(B.TLNO,3),'-', SUBSTRING(B.TLNO,4,4), '-',RIGHT(B.TLNO,4)) '전화번호'
FROM USED_GOODS_BOARD A, USED_GOODS_USER B
WHERE A.WRITER_ID = B.USER_ID
GROUP BY WRITER_ID
HAVING COUNT(BOARD_ID) >= 3
ORDER BY B.USER_ID DESC