SELECT YEAR(B.SALES_DATE) YEAR, MONTH(B.SALES_DATE) MONTH, A.GENDER, COUNT(DISTINCT B.USER_ID) USERS
FROM USER_INFO A, ONLINE_SALE B
WHERE A.USER_ID = B.USER_ID AND A.GENDER IS NOT NULL
GROUP BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE), A.GENDER
ORDER BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE), A.GENDER