SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, CASE 
WHEN FREEZER_YN IS NULL THEN 'N' 
WHEN FREEZER_YN = 'Y' THEN 'Y' 
WHEN FREEZER_YN = 'N' THEN 'N'
END AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE WAREHOUSE_NAME LIKE '%경기%'
ORDER BY WAREHOUSE_ID ASC
