# 상품을 구매한 회원수, 2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원 수
SELECT YEAR(O.SALES_DATE) YEAR, MONTH(O.SALES_DATE) MONTH, COUNT(DISTINCT O.USER_ID) PUCHASED_USERS, ROUND(COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '%2021%'), 1) PUCHASED_RATIO
FROM USER_INFO U LEFT JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
WHERE U.JOINED LIKE '%2021%' AND O.USER_ID IN (SELECT USER_ID
                                              FROM ONLINE_SALE)
GROUP BY YEAR, MONTH
ORDER BY YEAR(O.SALES_DATE) ASC, MONTH(O.SALES_DATE) ASC