SELECT A.PRODUCT_ID, A.PRODUCT_NAME, A.PRICE * SUM(B.AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT A, FOOD_ORDER B
WHERE A.PRODUCT_ID = B.PRODUCT_ID AND B.PRODUCE_DATE LIKE '%2022-05%'
GROUP BY B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC
