SELECT HISTORY_ID, CASE
WHEN DATEDIFF(END_DATE, START_DATE) +1 BETWEEN 7 AND 29
THEN ROUND((DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) +1)) * (SELECT (100-DISCOUNT_RATE)/100 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상'),0)
WHEN DATEDIFF(END_DATE, START_DATE) +1 BETWEEN 30 AND 89
THEN ROUND((DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) +1)) * (SELECT (100-DISCOUNT_RATE)/100 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상'),0)
WHEN DATEDIFF(END_DATE, START_DATE) +1 >= 90
THEN ROUND((DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) +1)) * (SELECT (100-DISCOUNT_RATE)/100 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상'),0)
ELSE DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) +1)
END FEE
FROM CAR_RENTAL_COMPANY_CAR A, CAR_RENTAL_COMPANY_RENTAL_HISTORY B
WHERE A.CAR_ID = B.CAR_ID AND A.CAR_TYPE = '트럭'
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC



# SELECT (100-DISCOUNT_RATE)/100 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상'


# SELECT (DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) +1)) * 0.92
# FROM CAR_RENTAL_COMPANY_CAR A, CAR_RENTAL_COMPANY_RENTAL_HISTORY B
# WHERE A.CAR_ID = B.CAR_ID AND A.CAR_TYPE = '트럭' AND HISTORY_ID = 724