SELECT USER_ID, NICKNAME, SUM(PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD A, USED_GOODS_USER B
WHERE STATUS = 'DONE' AND A.WRITER_ID = B.USER_ID
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC