SELECT B.USER_ID, B.NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD A, USED_GOODS_USER B
WHERE A.WRITER_ID = B.USER_ID AND STATUS = "DONE"
GROUP BY A.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC















# SELECT USER_ID, NICKNAME, SUM(PRICE) TOTAL_SALES
# FROM USED_GOODS_BOARD A, USED_GOODS_USER B
# WHERE STATUS = 'DONE' AND A.WRITER_ID = B.USER_ID
# GROUP BY USER_ID
# HAVING TOTAL_SALES >= 700000
# ORDER BY TOTAL_SALES ASC