SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d')
FROM MEMBER_PROFILE M LEFT JOIN REST_REVIEW R
ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_NAME IN 
(SELECT M.MEMBER_NAME
FROM MEMBER_PROFILE M LEFT JOIN REST_REVIEW R
ON M.MEMBER_ID = R.MEMBER_ID
GROUP BY M.MEMBER_NAME
HAVING COUNT(M.MEMBER_NAME) >= 
 (SELECT COUNT(M.MEMBER_NAME)
FROM MEMBER_PROFILE M LEFT JOIN REST_REVIEW R
ON M.MEMBER_ID = R.MEMBER_ID
GROUP BY M.MEMBER_NAME
ORDER BY COUNT(*) DESC LIMIT 1)
)
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC;

# SELECT M.MEMBER_NAME
# FROM MEMBER_PROFILE M LEFT JOIN REST_REVIEW R
# ON M.MEMBER_ID = R.MEMBER_ID
# GROUP BY M.MEMBER_NAME
# HAVING COUNT(M.MEMBER_NAME) >= (SELECT COUNT(M.MEMBER_NAME)
# FROM MEMBER_PROFILE M LEFT JOIN REST_REVIEW R
# ON M.MEMBER_ID = R.MEMBER_ID
# GROUP BY M.MEMBER_NAME
# ORDER BY COUNT(*) DESC LIMIT 1)
# ORDER BY RAND()