SELECT ITEM_TREE.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO, ITEM_TREE
WHERE ITEM_INFO.ITEM_ID = ITEM_TREE.ITEM_ID AND PARENT_ITEM_ID IN (SELECT ITEM_ID
FROM ITEM_INFO
WHERE RARITY = "RARE")
ORDER BY ITEM_ID DESC;


