-- 코드를 작성해주세요

SELECT YEAR(E.DIFFERENTIATION_DATE) YEAR,
(SELECT MAX(SIZE_OF_COLONY)
    FROM ECOLI_DATA SUB
    WHERE YEAR(SUB.DIFFERENTIATION_DATE) = YEAR(E.DIFFERENTIATION_DATE)
    GROUP BY YEAR(SUB.DIFFERENTIATION_DATE)
) - E.SIZE_OF_COLONY AS YEAR_DEV,
E.ID
FROM ECOLI_DATA E
ORDER BY YEAR, YEAR_DEV;