-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', B.BOARD_ID, "/", B.FILE_ID, B.FILE_NAME, B.FILE_EXT) FILE_PATH
FROM (SELECT BOARD_ID FROM USED_GOODS_BOARD
      GROUP BY BOARD_ID
      ORDER BY VIEWS DESC LIMIT 1
      )A, USED_GOODS_FILE B
WHERE A.BOARD_ID = B.BOARD_ID
ORDER BY B.FILE_ID DESC
