SELECT COUNT(A.ID) FISH_COUNT, MAX(A.LENGTH) AS MAX_LENGTH, A.FISH_TYPE
FROM (SELECT ID, FISH_TYPE, CASE
            WHEN LENGTH <= 10 THEN 10
            ELSE LENGTH
            END AS LENGTH FROM FISH_INFO) AS A
GROUP BY A.FISH_TYPE
HAVING AVG(A.LENGTH) >= 33
ORDER BY A.FISH_TYPE ASC;
